import Sidebar from '@/components/Sidebar'
import type { Metadata } from 'next'
import { Figtree } from 'next/font/google'
import './globals.css'
import SupabaseProvider from '@/Providers/SupabaseProvider'
import UserProvider from '@/Providers/UserProvider'
import ModalProvider from '@/Providers/ModalProvider'
import getSongsByUserId from '@/actions/getSongsByUserId'
import ToasterProvider from '@/Providers/ToasterProvider'
import Player from '@/components/Player'

const font = Figtree({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Beat Box - A Rythmic Adventure',
  description: 'Generated by create next app',
}
export const revalidate = 0;

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
   const userSongs = await getSongsByUserId(); 
  return (
    <html lang="en">
       <meta name="viewport" content="width=device-width, initial-scale=1.0"></meta>
      <body className={font.className}>   
      <ToasterProvider/>
        <SupabaseProvider>
          <UserProvider>
            <ModalProvider  />
            <Sidebar songs={userSongs}>
              {children}
            </Sidebar> 
            <Player />
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  )
}
